#!/usr/bin/env python3
import sys
from pathlib import Path


def main() -> int:
    if len(sys.argv) != 3:
        print("usage: gen_embedded_db.py <input_db.txt> <output_cpp>", file=sys.stderr)
        return 1

    input_path = Path(sys.argv[1])
    output_path = Path(sys.argv[2])

    data = input_path.read_bytes()

    lines = []
    lines.append("// Auto-generated by libretro/gen_embedded_db.py. Do not edit.")
    lines.append("#include <cstddef>")
    lines.append("")
    lines.append("const unsigned char geranes_libretro_embedded_db[] = {")

    bytes_per_line = 16
    for i in range(0, len(data), bytes_per_line):
        chunk = data[i:i + bytes_per_line]
        hexes = ", ".join(f"0x{b:02x}" for b in chunk)
        lines.append(f"    {hexes},")

    lines.append("};")
    lines.append("")
    lines.append(f"const unsigned int geranes_libretro_embedded_db_size = {len(data)}u;")
    lines.append("")

    output_path.write_text("\n".join(lines), encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
